services:  
  mongo:
    container_name: db_container_LDotR
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: "back-end"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: LDotR
    depends_on:
      - mongo      

  frontend:
    build:
      context: ./frontend
    container_name: "front-end"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - backend

volumes:
  mongo-data:



